version: "3.4"
services:
  # Web provides the Flask backend and frontend
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
      - FLASK_APP=biophi.common.web.views
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - HTTP_PROXY
      - HTTPS_PROXY
      - OASIS_DB_PATH=/data/OASis_9mers_v1.db
    volumes:
      - ./data/:/data
  # Redis provides the Redis in-memory database that serves as queue for Celery tasks
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  # Worker provides a Celery worker that processes tasks from the redis queue
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - FLASK_ENV=development
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - HTTP_PROXY
      - HTTPS_PROXY
      - OASIS_DB_PATH=/data/OASis_9mers_v1.db
    volumes:
      - ./data/:/data
    command: celery -A biophi.common.web.tasks.celery worker --loglevel=INFO
    depends_on:
      - redis





