channels:
  - nodefaults
  - bioconda
  - conda-forge
dependencies:
  - python = 3.13
  - pip
  - abnumber == 0.3.2
  - anarci == 2020.04.23
  - hmmer >= 3.1
  - pip:
      - click >= 7
      - pandas == 2.3.1
      - sqlalchemy == 2.0.41
      - flask < 3.0.0
      - werkzeug < 3.0.0
      - redis
      - celery
      - biopython
      - pytest
      - requests
      - tqdm
      - xlsxwriter
      - humanize
      - sapiens >= 1.1.0
